build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:stable
  amd64: ghcr.io/hassio-addons/base/amd64:stable
  armhf: ghcr.io/hassio-addons/base/armhf:stable
  armv7: ghcr.io/hassio-addons/base/armv7:stable
  i386: ghcr.io/hassio-addons/base/i386:stable
codenotary:
  base_image: codenotary@frenck.dev
  signer: www.wesley@gmail.com
